import { Hono } from "hono";
import * as Sentry from "@sentry/cloudflare";
import type { Bindings, Variables } from "./types";
import { authRoutes } from "./auth";
import { githubOAuthRoutes } from "./github-oauth";
import { apiRoutes } from "./drops";
import { buildOnboardJson, buildOnboardText } from "./onboard";
import { landingPage } from "./views/landing";
import { verifyPage } from "./views/verify";
import { viewerPage, passcodeGatePage } from "./views/viewer";
import { FAVICON_SVG } from "./views/favicon";
import { OG_SVG, dropOgSvg } from "./views/og-image";
import { renderDropOgPng, renderLandingOgPng } from "./views/og-png";
import { agentSkillsIndex, getSkillContent } from "./skill";
import { buildPatternIndex, getPatternMd } from "./patterns";
import {
  agentCard,
  linkHeader,
  llmsTxt,
  openApiSpec,
  robotsTxt,
  sitemapXml,
} from "./discoverability";
import { STYLES_CSS, STYLE_HREF } from "./styles";
import { FONTS } from "./fonts";
import {
  signUnlockToken,
  verifyPassword,
  verifyUnlockToken,
} from "./crypto";
import {
  bumpViewCount,
  getDrop,
  listVersions,
} from "./db";
import { isValidSlug } from "./slug";
import { apiError } from "./errors";

const app = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// Minimum acceptable TOKEN_PEPPER length. The dev pepper generated by
// scripts/setup.mjs is 64 hex chars (32 bytes); 32 chars is a generous
// floor that still rejects empty / placeholder values.
const MIN_PEPPER_LENGTH = 32;

// ----- Global security headers --------------------------------------------
//
// Applied to every response. The split:
//   - Universal:  HSTS, X-Content-Type-Options, Referrer-Policy, Permissions-Policy.
//   - text/html:  X-Frame-Options + Content-Security-Policy (unless the handler
//                 already set its own CSP — /p/:slug/raw does for the iframed
//                 user-uploaded HTML; we don't overwrite it).
//   - application/json + linkset+json: default-src 'none' (defense in depth).
//
// CORS is intentionally NOT set anywhere: htmlbin is an agent-side API.
// Disallowing browser cross-origin XHR is a feature — it prevents a random
// third-party site from making authenticated calls with the user's token.
// If you find yourself wanting to add CORS, talk to the user first.
app.use("*", async (c, next) => {
  await next();
  const ct = c.res.headers.get("content-type") ?? "";

  c.res.headers.set(
    "Strict-Transport-Security",
    "max-age=31536000; includeSubDomains; preload"
  );
  c.res.headers.set("X-Content-Type-Options", "nosniff");
  c.res.headers.set("Referrer-Policy", "strict-origin-when-cross-origin");
  c.res.headers.set(
    "Permissions-Policy",
    "geolocation=(), camera=(), microphone=(), payment=(), usb=()"
  );

  if (ct.startsWith("text/html")) {
    // Don't clobber a handler-set CSP (e.g. /p/:slug/raw uses a different one
    // to allow the viewer to iframe it).
    if (!c.res.headers.has("content-security-policy")) {
      c.res.headers.set("X-Frame-Options", "SAMEORIGIN");
      const sentryOn = !!c.env.SENTRY_DSN;
      const scriptSrc = sentryOn
        ? "script-src 'self' 'unsafe-inline' https://js.sentry-cdn.com"
        : "script-src 'self' 'unsafe-inline'";
      const connectSrc = sentryOn
        ? "connect-src 'self' https://*.ingest.sentry.io https://*.ingest.us.sentry.io"
        : "connect-src 'self'";
      c.res.headers.set(
        "Content-Security-Policy",
        [
          "default-src 'self'",
          "img-src 'self' data: https:",
          // No external font origins now that we self-host Geist/Geist Mono.
          "style-src 'self' 'unsafe-inline'",
          "font-src 'self'",
          scriptSrc,
          connectSrc,
          "frame-src 'self'",
          "frame-ancestors 'none'",
          "base-uri 'none'",
        ].join("; ")
      );
    }
  } else if (
    ct.startsWith("application/json") ||
    ct.startsWith("application/linkset+json")
  ) {
    if (!c.res.headers.has("content-security-policy")) {
      c.res.headers.set("Content-Security-Policy", "default-src 'none'");
    }
  }
});

// ----- Required-config check ----------------------------------------------
//
// TOKEN_PEPPER is required for token hashing AND for HMAC-signed unlock
// cookies on passcode-protected drops. An empty/missing pepper causes
// `crypto.subtle.importKey` to throw `DataError: Imported HMAC key length
// (0)…` deep in the request — surfacing as an opaque 500. Catch it at the
// edge with a clear, machine-readable error so misconfigured deploys are
// loud, not silently broken.
app.use("*", async (c, next) => {
  const pepper = c.env.TOKEN_PEPPER;
  if (typeof pepper !== "string" || pepper.length < MIN_PEPPER_LENGTH) {
    return apiError(
      c,
      "server_misconfigured",
      "TOKEN_PEPPER secret is missing or too short. Set it with `wrangler secret put TOKEN_PEPPER`.",
      503
    );
  }
  await next();
});

// ----- Public landing -----------------------------------------------------
app.on(["GET", "HEAD"], "/", async (c) => {
  // Content-negotiation: agents asking for Markdown get the landing as
  // Markdown via Workers AI's toMarkdown. Same idea as Cloudflare's
  // "Markdown for Agents" pattern. Humans still get the regular HTML.
  const accept = c.req.header("Accept") ?? "";
  if (acceptsMarkdown(accept) || c.req.query("format") === "md") {
    return landingAsMarkdown(c);
  }
  c.header("Link", linkHeader(c.env.PUBLIC_URL));
  return c.html(landingPage(c.env));
});

// Explicit URL form for the markdown view of the landing — easy to
// discover, easy to link to from /api/onboard or llms.txt.
app.on(["GET", "HEAD"], "/index.md", (c) => landingAsMarkdown(c));

async function landingAsMarkdown(c: any): Promise<Response> {
  const cacheKey = `md:landing`;
  const cached = await c.env.DROPS_KV.get(cacheKey);
  if (cached) {
    return new Response(cached, { headers: mdHeaders() });
  }

  const html = landingPage(c.env);
  let markdown = "";
  try {
    const results = await c.env.AI.toMarkdown([
      { name: "index.html", blob: new Blob([html], { type: "text/html" }) },
    ]);
    markdown = results?.[0]?.data ?? "";
  } catch (e) {
    return c.json(
      {
        error: "markdown_unavailable",
        detail:
          "Markdown conversion requires Workers AI. Available in production; in `wrangler dev` use --remote.",
      },
      503
    );
  }

  // Landing copy changes rarely — cache 1 hour at the edge.
  c.executionCtx.waitUntil(
    c.env.DROPS_KV.put(cacheKey, markdown, { expirationTtl: 3600 })
  );
  return new Response(markdown, { headers: mdHeaders() });
}

function acceptsMarkdown(accept: string): boolean {
  // Look for text/markdown explicitly (and beat a wildcard text/* with HTML).
  const a = accept.toLowerCase();
  if (!a.includes("text/markdown")) return false;
  // If the client also accepts HTML at higher-or-equal weight, prefer HTML.
  // Quick heuristic: if the markdown token comes before text/html in the
  // Accept string, agent is asking for markdown first.
  const md = a.indexOf("text/markdown");
  const html = a.indexOf("text/html");
  return html === -1 || md < html;
}

// ----- Global stylesheet (single source of truth across pages) -----------
//
// Cache for an hour at the browser, a week at the edge. The CSS contents
// can change between deploys; if you need stronger guarantees, switch to
// a content-hashed filename (e.g. /style.<hash>.css) and bump to
// immutable.
app.get("/style.css", (c) => {
  return new Response(STYLES_CSS, {
    headers: {
      "Content-Type": "text/css; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=604800",
    },
  });
});

// ----- Sentry browser loader --------------------------------------------
//
// Emits a self-bootstrapping script: injects Sentry's CDN loader, then
// init's with our DSN. When SENTRY_DSN is unset (dev or pre-setup) we
// return a no-op body so the <script> tag in chrome stays harmless.
// DSN is public by design — Sentry expects it in client code.
app.on(["GET", "HEAD"], "/sentry.js", (c) => {
  const dsn = c.env.SENTRY_DSN;
  const headers = {
    "Content-Type": "application/javascript; charset=utf-8",
    "Cache-Control": "public, max-age=3600",
  };
  if (!dsn) return new Response("/* sentry disabled — no DSN */", { headers });
  // DSN shape: https://<publicKey>@oXXXXX.ingest.sentry.io/<project>
  const m = /\/\/([^@]+)@/.exec(dsn);
  if (!m) return new Response("/* sentry: malformed DSN */", { headers });
  const publicKey = m[1];
  const dsnJson = JSON.stringify(dsn);
  const keyJson = JSON.stringify(publicKey);
  const body = `(function(){var s=document.createElement('script');s.src='https://js.sentry-cdn.com/'+${keyJson}+'.min.js';s.crossOrigin='anonymous';s.onload=function(){if(window.Sentry)window.Sentry.init({dsn:${dsnJson},tracesSampleRate:0.1});};document.head.appendChild(s);})();`;
  return new Response(body, { headers });
});

// ----- Self-hosted Geist + Geist Mono fonts ------------------------------
//
// Bundled into the Worker (see wrangler.toml [[rules]] type="Data").
// Served same-origin so we avoid the Google Fonts CSS round-trip, which
// Lighthouse measured at ~750ms of render-blocking time on Slow 4G.
// Filenames are content-stable (Geist-400.woff2 etc.); cache forever.
app.on(["GET", "HEAD"], "/fonts/:name", (c) => {
  const name = c.req.param("name");
  const body = FONTS[name];
  if (!body) return c.notFound();
  return new Response(body, {
    headers: {
      "Content-Type": "font/woff2",
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
});

// ----- Favicon (single SVG, light + dark adaptive) -----------------------
app.get("/favicon.svg", () => {
  return new Response(FAVICON_SVG, {
    headers: {
      "Content-Type": "image/svg+xml",
      "Cache-Control": "public, max-age=86400, s-maxage=604800",
    },
  });
});
// Browsers still hit /favicon.ico unconditionally — point them at the SVG
// (browsers handle the mime type; we send a 301 to keep things tidy).
app.get("/favicon.ico", (c) => c.redirect("/favicon.svg", 301));

// ----- Open Graph images ------------------------------------------------
//
// We serve both PNG and SVG variants. The PNG is what `og:image` meta
// tags point at — Slack, Twitter, iMessage, and Facebook do not render
// SVG og:images, so PNG is non-negotiable for social previews. The SVG
// stays around for direct viewing/embedding (it's tiny and crisp).
//
// PNG rendering goes through satori → resvg-wasm. KV caches the rendered
// bytes per slug+version so each unique drop's OG card is rendered once,
// not once per Slack/Twitter/iMessage preview bot.

app.get("/og.svg", () => {
  return new Response(OG_SVG, {
    headers: {
      "Content-Type": "image/svg+xml",
      "Cache-Control": "public, max-age=86400, s-maxage=2592000",
    },
  });
});

app.get("/og.png", async (c) => {
  const cacheKey = "og-png:landing:v3";
  const cached = await c.env.DROPS_KV.get(cacheKey, { type: "arrayBuffer" });
  if (cached) return pngResponse(cached, true);

  try {
    const png = await renderLandingOgPng(c.env, { publicUrl: c.env.PUBLIC_URL });
    c.executionCtx.waitUntil(
      c.env.DROPS_KV.put(cacheKey, png.buffer, {
        expirationTtl: 60 * 60 * 24 * 7,
      })
    );
    return pngResponse(png.buffer);
  } catch (e) {
    // Render failure is logged for ops; we fall back to the SVG so the
    // social preview still works. No internal details exposed to clients.
    console.error("og.png landing render failed", e);
    return c.redirect("/og.svg", 302);
  }
});

// Per-drop OG card. Cached per slug+version: any new version invalidates
// the cache (different key), so social previews update within Slack /
// Twitter's own unfurl TTLs.
app.get("/p/:slug/og.svg", async (c) => {
  const slug = c.req.param("slug");
  if (!isValidSlug(slug)) return c.notFound();
  const drop = await getDrop(c.env.DB, slug);
  if (!drop) return c.notFound();
  const svg = dropOgSvg({
    slug: drop.slug,
    title: drop.title,
    isLocked: !!drop.password_hash,
    latestVersion: drop.latest_version,
    updatedAt: drop.updated_at,
    publicUrl: c.env.PUBLIC_URL,
  });
  return new Response(svg, {
    headers: {
      "Content-Type": "image/svg+xml",
      "Cache-Control": "public, max-age=300, s-maxage=600",
    },
  });
});

app.get("/p/:slug/og.png", async (c) => {
  const slug = c.req.param("slug");
  if (!isValidSlug(slug)) return c.notFound();
  const drop = await getDrop(c.env.DB, slug);
  if (!drop) return c.notFound();

  const cacheKey = `og-png:${slug}:v${drop.latest_version}:r3`;
  const cached = await c.env.DROPS_KV.get(cacheKey, { type: "arrayBuffer" });
  if (cached) return pngResponse(cached, true);

  try {
    const png = await renderDropOgPng(c.env, {
      slug: drop.slug,
      title: drop.title,
      isLocked: !!drop.password_hash,
      latestVersion: drop.latest_version,
      updatedAt: drop.updated_at,
      publicUrl: c.env.PUBLIC_URL,
    });
    c.executionCtx.waitUntil(
      c.env.DROPS_KV.put(cacheKey, png.buffer, {
        expirationTtl: 60 * 60 * 24 * 30,
      })
    );
    return pngResponse(png.buffer);
  } catch (e) {
    // Render failure shouldn't 500 the social preview — Slack will just
    // skip the image. Fall back to the SVG endpoint, which always works.
    // Errors are logged for ops; no internal details exposed to clients.
    console.error("og.png drop render failed", slug, e);
    return c.redirect(`/p/${slug}/og.svg`, 302);
  }
});

function pngResponse(body: ArrayBuffer, fromCache = false): Response {
  return new Response(body, {
    headers: {
      "Content-Type": "image/png",
      "Cache-Control": "public, max-age=300, s-maxage=86400",
      "X-Og-Cache": fromCache ? "hit" : "miss",
    },
  });
}

// ----- Agent-ready discoverability ---------------------------------------
app.on(["GET", "HEAD"], "/robots.txt", (c) => {
  return new Response(robotsTxt(c.env.PUBLIC_URL), {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
});
app.on(["GET", "HEAD"], "/llms.txt", (c) => {
  return new Response(llmsTxt(c.env.PUBLIC_URL), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=300",
    },
  });
});
app.on(["GET", "HEAD"], "/sitemap.xml", (c) => {
  return new Response(sitemapXml(c.env.PUBLIC_URL), {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
});
app.on(["GET", "HEAD"], "/.well-known/agent-card.json", (c) => {
  return c.json(agentCard(c.env.PUBLIC_URL));
});
app.on(["GET", "HEAD"], "/openapi.json", (c) => {
  return c.json(openApiSpec(c.env.PUBLIC_URL));
});

// RFC 9116 — security contact for vulnerability disclosure.
app.on(["GET", "HEAD"], "/.well-known/security.txt", (c) => {
  const host = c.env.PUBLIC_URL.replace(/\/$/, "");
  // Expires one year out. Update this annually.
  const body = [
    "Contact: mailto:security@htmlbin.dev",
    "Expires: 2027-05-10T00:00:00.000Z",
    "Preferred-Languages: en",
    `Canonical: ${host}/.well-known/security.txt`,
    `Policy: ${host}/.well-known/security.txt`,
    "",
  ].join("\n");
  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=86400",
    },
  });
});

// Agent Skills Discovery (RFC v0.2.0). Both routes support GET + HEAD
// per spec. SKILL.md is bundled at build time from skills/htmlbin/SKILL.md.
app.on(["GET", "HEAD"], "/.well-known/agent-skills/index.json", async (c) => {
  const index = await agentSkillsIndex(c.env.PUBLIC_URL);
  return new Response(JSON.stringify(index, null, 2), {
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "public, max-age=300, s-maxage=3600",
    },
  });
});
app.on(["GET", "HEAD"], "/.well-known/agent-skills/htmlbin/SKILL.md", () => {
  return new Response(getSkillContent(), {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Cache-Control": "public, max-age=300, s-maxage=3600",
    },
  });
});

// Pattern catalog. The deployed skill teaches agents the file-based pattern
// convention (./.htmlbin/patterns/*.md and ~/.config/htmlbin/patterns/*.md);
// when nothing is installed locally, the agent fetches the official starter
// pack from here. Patterns are agent-side guidance, not server-rendered
// templates — the Worker just serves the markdown.
app.on(["GET", "HEAD"], "/.well-known/patterns/index.json", (c) => {
  return new Response(
    JSON.stringify(buildPatternIndex(c.env.PUBLIC_URL), null, 2),
    {
      headers: {
        "Content-Type": "application/json; charset=utf-8",
        "Cache-Control": "public, max-age=300, s-maxage=3600",
      },
    }
  );
});
app.on(["GET", "HEAD"], "/.well-known/patterns/:filename", (c) => {
  const filename = c.req.param("filename");
  const md = getPatternMd(filename);
  if (!md) return apiError(c, "not_found", "Pattern not found.", 404);
  return new Response(md, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Cache-Control": "public, max-age=300, s-maxage=3600",
    },
  });
});

// API Catalog (RFC 9727). application/linkset+json describing the API
// surface — link relations point to the OpenAPI spec, llms.txt as
// service-doc, and the well-known agent-card as a status-adjacent
// descriptor (htmlbin has no separate health endpoint).
app.on(["GET", "HEAD"], "/.well-known/api-catalog", (c) => {
  const host = c.env.PUBLIC_URL.replace(/\/$/, "");
  const catalog = {
    linkset: [
      {
        anchor: `${host}/api/`,
        "service-desc": [
          {
            href: `${host}/openapi.json`,
            type: "application/openapi+json",
          },
        ],
        "service-doc": [
          { href: `${host}/api/onboard`, type: "application/json" },
          { href: `${host}/llms.txt`, type: "text/plain" },
        ],
        status: [
          { href: `${host}/.well-known/agent-card.json`, type: "application/json" },
        ],
      },
    ],
  };
  return new Response(JSON.stringify(catalog, null, 2), {
    headers: {
      "Content-Type": "application/linkset+json",
      "Cache-Control": "public, max-age=300, s-maxage=3600",
    },
  });
});

// ----- Agent onboarding ---------------------------------------------------
//
// JSON is the default. The descriptor is data — endpoints, methods, body
// schemas — not prose for an agent to "follow." That distinction matters:
// agents are trained to be wary of "fetch a URL and execute its
// instructions" patterns (textbook prompt injection), and a structured
// JSON document slips through that filter without friction.
//
// Markdown is still served for humans previewing the API — request it
// with `Accept: text/markdown` or `?format=md`.
app.on(["GET", "HEAD"], "/api/onboard", (c) => {
  const accept = c.req.header("Accept") ?? "";
  const wantsMarkdown =
    accept.toLowerCase().includes("text/markdown") ||
    c.req.query("format") === "md";
  if (wantsMarkdown) {
    const text = buildOnboardText(c.env.PUBLIC_URL);
    return new Response(text, {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        Vary: "Accept",
      },
    });
  }
  c.header("Vary", "Accept");
  return c.json(buildOnboardJson(c.env.PUBLIC_URL));
});

// ----- Auth + API ---------------------------------------------------------
app.route("/api", authRoutes);
app.route("/api", apiRoutes);

// ----- Human verification page -------------------------------------------
//
// The human handoff used to live at POST /verify with a Turnstile widget +
// optional "paste existing token" field. It's now a single "Sign in with
// GitHub" button that hands off to githubOAuthRoutes (/auth/github/*).
// Identity is bound to github_user_id, which is UNIQUE per htmlbin
// account — cycling tokens no longer creates fresh accounts.
app.get("/verify", (c) => {
  const code = c.req.query("code") ?? "";
  return c.html(verifyPage(c.env, { code }));
});

app.route("/", githubOAuthRoutes);

// ----- Public prototype viewer ------------------------------------------
app.on(["GET", "HEAD"], "/p/:slug", async (c) => {
  const slug = c.req.param("slug");
  if (!isValidSlug(slug)) return c.notFound();

  const drop = await getDrop(c.env.DB, slug);
  if (!drop) return c.notFound();

  const locked = !!drop.password_hash;
  let unlocked = !locked;
  if (locked) {
    const cookie = getCookie(c.req.header("Cookie") ?? "", `wu_${slug}`);
    if (cookie) {
      unlocked = await verifyUnlockToken(cookie, slug, c.env.TOKEN_PEPPER);
    }
  }

  // Optional ?v=N pins to a specific version; default = latest.
  const versionParam = c.req.query("v");
  let viewVersion = drop.latest_version;
  if (versionParam) {
    const n = parseInt(versionParam, 10);
    if (
      Number.isFinite(n) &&
      n >= 1 &&
      n <= drop.latest_version
    ) {
      viewVersion = n;
    }
  }

  const versions = await listVersions(c.env.DB, slug);

  c.executionCtx.waitUntil(bumpViewCount(c.env.DB, slug));

  return c.html(
    viewerPage(c.env, drop, {
      locked,
      unlocked,
      versions: versions.map((v) => ({
        version: v.version,
        size_bytes: v.size_bytes,
        has_context: !!v.context,
        context: v.context,
        created_at: v.created_at,
      })),
      viewVersion,
    })
  );
});

app.post("/p/:slug/unlock", async (c) => {
  const slug = c.req.param("slug");
  if (!isValidSlug(slug)) return c.notFound();
  const drop = await getDrop(c.env.DB, slug);
  if (!drop) return c.notFound();
  if (!drop.password_hash || !drop.password_salt) {
    return c.redirect(`/p/${slug}`, 302);
  }

  const form = await c.req.formData();
  const passcode = String(form.get("passcode") ?? "");
  const ok = await verifyPassword(
    passcode,
    drop.password_salt,
    drop.password_hash
  );
  if (!ok) {
    return c.html(passcodeGatePage(c.env, drop, { error: true }));
  }

  // 24-hour signed unlock cookie, scoped to this slug.
  const exp = Date.now() + 24 * 3600 * 1000;
  const value = await signUnlockToken(slug, exp, c.env.TOKEN_PEPPER);
  const cookie = `wu_${slug}=${value}; Path=/p/${slug}; HttpOnly; Secure; SameSite=Lax; Max-Age=${24 * 3600}`;
  return new Response(null, {
    status: 302,
    headers: {
      Location: `/p/${slug}`,
      "Set-Cookie": cookie,
    },
  });
});

// Re-lock: clear the unlock cookie and bounce back to the gate.
// Only side-effect is on the caller's own cookie, so no auth or CSRF
// token needed (a forged form would just log the forger out of nothing).
app.post("/p/:slug/lock", async (c) => {
  const slug = c.req.param("slug");
  if (!isValidSlug(slug)) return c.notFound();
  const drop = await getDrop(c.env.DB, slug);
  if (!drop) return c.notFound();
  // Same Path as the original cookie so the browser actually expires it.
  const cookie = `wu_${slug}=; Path=/p/${slug}; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;
  return new Response(null, {
    status: 302,
    headers: { Location: `/p/${slug}`, "Set-Cookie": cookie },
  });
});

app.on(["GET", "HEAD"], "/p/:slug/raw", async (c) => {
  const slug = c.req.param("slug");
  if (!isValidSlug(slug)) return c.notFound();

  const drop = await getDrop(c.env.DB, slug);
  if (!drop) return c.notFound();

  if (drop.password_hash) {
    const cookie = getCookie(c.req.header("Cookie") ?? "", `wu_${slug}`);
    const ok =
      !!cookie &&
      (await verifyUnlockToken(cookie, slug, c.env.TOKEN_PEPPER));
    if (!ok) {
      // Don't expose locked HTML — redirect to the gate.
      return c.redirect(`/p/${slug}`, 302);
    }
  }

  // ?v=N selects a specific version; default = latest.
  let v = drop.latest_version;
  const vp = c.req.query("v");
  if (vp) {
    const n = parseInt(vp, 10);
    if (Number.isFinite(n) && n >= 1 && n <= drop.latest_version) v = n;
  }

  const html = await c.env.DROPS_KV.get(`html:${slug}:v${v}`);
  if (!html) return c.notFound();

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": drop.password_hash
        ? "private, no-store"
        : "public, max-age=60, s-maxage=300",
      "X-Robots-Tag": "noindex",
      // Defense-in-depth for the served HTML:
      "X-Content-Type-Options": "nosniff",
      "Referrer-Policy": "no-referrer",
      // CSP: allow inline scripts/styles (drops are user-authored), but block
      // top-level navigation hijacking and disallow being framed by other origins.
      "Content-Security-Policy":
        "frame-ancestors 'self'; base-uri 'none'; form-action 'self' https:",
    },
  });
});

// ----- 404 ----------------------------------------------------------------
app.notFound((c) => {
  return c.html(notFoundHtml(c.env.PUBLIC_URL), 404);
});

// ----- Helpers ------------------------------------------------------------

function mdHeaders(): Record<string, string> {
  return {
    "Content-Type": "text/markdown; charset=utf-8",
    "Cache-Control": "public, max-age=300, s-maxage=3600",
    "Vary": "Accept",
  };
}

function getCookie(header: string, name: string): string | null {
  for (const part of header.split(/;\s*/)) {
    const eq = part.indexOf("=");
    if (eq === -1) continue;
    if (part.slice(0, eq) === name) return part.slice(eq + 1);
  }
  return null;
}

function notFoundHtml(publicUrl: string): string {
  const host = publicUrl.replace(/^https?:\/\//, "");
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
  return /* html */ `<!doctype html>
<html><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />
<title>404 · htmlbin</title>
<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
<link rel="stylesheet" href="${STYLE_HREF}" />
</head>
<body>
<header class="page-head">
  <div class="row">
    <div class="crumb">
      <a href="/" class="wordmark">htmlbin</a>
      <span class="slash">/</span>
      <span class="verb">GET</span>
      <span class="path">/p/&lt;unknown&gt;</span>
      <span class="ver">v1</span>
    </div>
    <div class="head-meta">
      <a href="/htmlbin">/htmlbin</a>
      <a href="/api/onboard">/api/onboard</a>
    </div>
  </div>
</header>
<main>
  <details class="req" aria-label="memo">
    <summary class="reqline"><span class="verb">GET</span> <span class="path">/p/&lt;unknown&gt;</span> <span class="proto">HTTP/1.1</span></summary>
    <div class="rows">
      <div class="row"><span class="k">host</span><span class="v">${host}</span></div>
      <div class="row"><span class="k">date</span><span class="v">${date}</span></div>
      <div class="resline"><span class="bad">404 Not Found</span> &nbsp; content-type: text/plain</div>
    </div>
  </details>
  <hr class="rule" />
  <div class="notfound">
    <div class="stamp">return to sender</div>
    <h1>This drop doesn't exist.</h1>
    <p>The slug you opened was either never created, or has since been deleted by the agent that owned it. <a href="${publicUrl}">Back to htmlbin</a>.</p>
  </div>
</main>
</body></html>`;
}

// Wrapped in Sentry. DSN is read from env at request time; when
// SENTRY_DSN is unset (dev or pre-setup) the SDK no-ops cleanly.
const handler: ExportedHandler<Bindings> = {
  fetch: (request, env, ctx) => app.fetch(request, env, ctx),
};

export default Sentry.withSentry(
  (env: Bindings) => ({
    dsn: env.SENTRY_DSN,
    tracesSampleRate: 0.1,
    sendDefaultPii: false,
  }),
  handler,
);
